from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
                            QRect, QSize, QUrl, Qt, QDate)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
                           QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
                           QRadialGradient)
from PySide2.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(597, 729)
        self.verticalLayout = QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QFrame(Dialog)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_19 = QFrame(self.frame)
        self.frame_19.setMaximumSize(QSize(16777215, 30))
        self.frame_19.setFrameShape(QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout = QHBoxLayout(self.frame_19)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_11 = QLabel(self.frame_19)
        self.label_11.setMinimumSize(QSize(110, 0))
        self.label_11.setMaximumSize(QSize(110, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.plainTextEdit = QPlainTextEdit(self.frame_19)
        self.plainTextEdit.setMaximumSize(QSize(16777215, 30))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout.addWidget(self.plainTextEdit)
        self.verticalLayout_2.addWidget(self.frame_19)
        self.frame_18 = QFrame(self.frame)
        self.frame_18.setMaximumSize(QSize(16777215, 30))
        self.frame_18.setFrameShape(QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_2 = QHBoxLayout(self.frame_18)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_12 = QLabel(self.frame_18)
        self.label_12.setMinimumSize(QSize(110, 0))
        self.label_12.setMaximumSize(QSize(110, 16777215))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.plainTextEdit_2 = QPlainTextEdit(self.frame_18)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.horizontalLayout_2.addWidget(self.plainTextEdit_2)
        self.verticalLayout_2.addWidget(self.frame_18)
        self.frame_17 = QFrame(self.frame)
        self.frame_17.setMaximumSize(QSize(16777215, 30))
        self.frame_17.setFrameShape(QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_3 = QHBoxLayout(self.frame_17)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_13 = QLabel(self.frame_17)
        self.label_13.setMinimumSize(QSize(110, 0))
        self.label_13.setMaximumSize(QSize(110, 16777215))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.plainTextEdit_3 = QPlainTextEdit(self.frame_17)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.horizontalLayout_3.addWidget(self.plainTextEdit_3)
        self.verticalLayout_2.addWidget(self.frame_17)
        self.frame_16 = QFrame(self.frame)
        self.frame_16.setMaximumSize(QSize(16777215, 30))
        self.frame_16.setFrameShape(QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_4 = QHBoxLayout(self.frame_16)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_14 = QLabel(self.frame_16)
        self.label_14.setMinimumSize(QSize(110, 0))
        self.label_14.setMaximumSize(QSize(110, 16777215))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_4.addWidget(self.label_14)
        self.dateEdit = QDateEdit(self.frame_16)
        self.dateEdit.setMaximumDate(QDate(2022, 12, 31))
        self.dateEdit.setMinimumDate(QDate(1900, 9, 14))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setCurrentSectionIndex(0)
        self.dateEdit.setTimeSpec(Qt.LocalTime)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_4.addWidget(self.dateEdit)
        self.verticalLayout_2.addWidget(self.frame_16)
        self.frame_9 = QFrame(self.frame)
        self.frame_9.setMinimumSize(QSize(0, 30))
        self.frame_9.setMaximumSize(QSize(16777215, 30))
        self.frame_9.setFrameShape(QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_11 = QHBoxLayout(self.frame_9)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_3 = QLabel(self.frame_9)
        self.label_3.setMinimumSize(QSize(110, 0))
        self.label_3.setMaximumSize(QSize(110, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_11.addWidget(self.label_3)
        self.plainTextEdit_6 = QPlainTextEdit(self.frame_9)
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.horizontalLayout_11.addWidget(self.plainTextEdit_6)
        self.verticalLayout_2.addWidget(self.frame_9)
        self.frame_15 = QFrame(self.frame)
        self.frame_15.setFrameShape(QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_5 = QHBoxLayout(self.frame_15)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_15 = QLabel(self.frame_15)
        self.label_15.setMinimumSize(QSize(110, 0))
        self.label_15.setMaximumSize(QSize(110, 16777215))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.comboBox = QComboBox(self.frame_15)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox)
        self.verticalLayout_2.addWidget(self.frame_15)
        self.frame_14 = QFrame(self.frame)
        self.frame_14.setMaximumSize(QSize(16777215, 30))
        self.frame_14.setFrameShape(QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_6 = QHBoxLayout(self.frame_14)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_16 = QLabel(self.frame_14)
        self.label_16.setMinimumSize(QSize(110, 0))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_6.addWidget(self.label_16)
        self.textEdit = QTextEdit(self.frame_14)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_6.addWidget(self.textEdit)
        self.verticalLayout_2.addWidget(self.frame_14)
        self.frame_13 = QFrame(self.frame)
        self.frame_13.setMaximumSize(QSize(16777215, 30))
        self.frame_13.setFrameShape(QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_7 = QHBoxLayout(self.frame_13)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_17 = QLabel(self.frame_13)
        self.label_17.setMinimumSize(QSize(110, 0))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.plainTextEdit_4 = QPlainTextEdit(self.frame_13)
        self.plainTextEdit_4.setMaximumSize(QSize(16777215, 30))
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.horizontalLayout_7.addWidget(self.plainTextEdit_4)
        self.verticalLayout_2.addWidget(self.frame_13)
        self.frame_12 = QFrame(self.frame)
        self.frame_12.setMaximumSize(QSize(16777215, 30))
        self.frame_12.setFrameShape(QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_8 = QHBoxLayout(self.frame_12)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_18 = QLabel(self.frame_12)
        self.label_18.setMinimumSize(QSize(110, 0))
        self.label_18.setMaximumSize(QSize(110, 16777215))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_8.addWidget(self.label_18)
        self.dateEdit_2 = QDateEdit(self.frame_12)
        self.dateEdit_2.setDate(QDate(2019, 1, 1))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout_8.addWidget(self.dateEdit_2)
        self.verticalLayout_2.addWidget(self.frame_12)
        self.frame_11 = QFrame(self.frame)
        self.frame_11.setFrameShape(QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_9 = QHBoxLayout(self.frame_11)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QLabel(self.frame_11)
        self.label.setMinimumSize(QSize(110, 0))
        self.label.setMaximumSize(QSize(110, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.frame_20 = QFrame(self.frame_11)
        self.frame_20.setMinimumSize(QSize(0, 150))
        self.frame_20.setFrameShape(QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout = QGridLayout(self.frame_20)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_24 = QCheckBox(self.frame_20)
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout.addWidget(self.checkBox_24, 8, 4, 1, 1)
        self.checkBox_5 = QCheckBox(self.frame_20)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 3, 2, 2, 1)
        self.checkBox_12 = QCheckBox(self.frame_20)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout.addWidget(self.checkBox_12, 13, 4, 1, 1)
        self.checkBox_21 = QCheckBox(self.frame_20)
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout.addWidget(self.checkBox_21, 5, 4, 3, 1)
        self.checkBox_2 = QCheckBox(self.frame_20)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 0, 2, 1, 1)
        self.checkBox_17 = QCheckBox(self.frame_20)
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout.addWidget(self.checkBox_17, 1, 2, 2, 1)
        self.checkBox_22 = QCheckBox(self.frame_20)
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout.addWidget(self.checkBox_22, 5, 0, 1, 1)
        self.checkBox_11 = QCheckBox(self.frame_20)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout.addWidget(self.checkBox_11, 11, 2, 3, 1)
        self.checkBox_14 = QCheckBox(self.frame_20)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout.addWidget(self.checkBox_14, 14, 2, 2, 2)
        self.checkBox_50 = QCheckBox(self.frame_20)
        self.checkBox_50.setObjectName("checkBox_50")
        self.gridLayout.addWidget(self.checkBox_50, 14, 3, 2, 2)
        self.checkBox_4 = QCheckBox(self.frame_20)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 3, 0, 1, 2)
        self.checkBox_23 = QCheckBox(self.frame_20)
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout.addWidget(self.checkBox_23, 5, 2, 1, 1)
        self.checkBox = QCheckBox(self.frame_20)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 2)
        self.checkBox_20 = QCheckBox(self.frame_20)
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout.addWidget(self.checkBox_20, 10, 2, 1, 1)
        self.checkBox_9 = QCheckBox(self.frame_20)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout.addWidget(self.checkBox_9, 9, 4, 2, 1)
        self.checkBox_3 = QCheckBox(self.frame_20)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 0, 4, 1, 1)
        self.checkBox_6 = QCheckBox(self.frame_20)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 3, 4, 2, 1)
        self.checkBox_19 = QCheckBox(self.frame_20)
        self.checkBox_19.setObjectName("checkBox_19")
        self.gridLayout.addWidget(self.checkBox_19, 13, 0, 1, 1)
        self.checkBox_13 = QCheckBox(self.frame_20)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout.addWidget(self.checkBox_13, 14, 0, 2, 2)
        self.checkBox_8 = QCheckBox(self.frame_20)
        self.checkBox_8.setTristate(False)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout.addWidget(self.checkBox_8, 7, 2, 3, 1)
        self.checkBox_7 = QCheckBox(self.frame_20)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 7, 0, 3, 2)
        self.checkBox_18 = QCheckBox(self.frame_20)
        self.checkBox_18.setObjectName("checkBox_18")
        self.gridLayout.addWidget(self.checkBox_18, 2, 4, 1, 1)
        self.checkBox_16 = QCheckBox(self.frame_20)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout.addWidget(self.checkBox_16, 2, 0, 1, 1)
        self.checkBox_10 = QCheckBox(self.frame_20)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout.addWidget(self.checkBox_10, 10, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.frame_20)
        self.verticalLayout_2.addWidget(self.frame_11)
        self.frame_10 = QFrame(self.frame)
        self.frame_10.setFrameShape(QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_10 = QHBoxLayout(self.frame_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_2 = QLabel(self.frame_10)
        self.label_2.setMinimumSize(QSize(110, 0))
        self.label_2.setMaximumSize(QSize(110, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.pushButton = QPushButton(self.frame_10)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.label_19 = QLabel(self.frame_10)
        self.label_19.setMinimumSize(QSize(140, 0))
        self.label_19.setMaximumSize(QSize(140, 16777215))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_10.addWidget(self.label_19)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.frame_8 = QFrame(self.frame)
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_12 = QHBoxLayout(self.frame_8)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_4 = QLabel(self.frame_8)
        self.label_4.setMinimumSize(QSize(110, 0))
        self.label_4.setMaximumSize(QSize(110, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        self.radioButton = QRadioButton(self.frame_8)
        self.radioButton.setMinimumSize(QSize(110, 0))
        self.radioButton.setMaximumSize(QSize(110, 16777215))
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_12.addWidget(self.radioButton)
        self.radioButton_2 = QRadioButton(self.frame_8)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_12.addWidget(self.radioButton_2)
        self.verticalLayout_2.addWidget(self.frame_8)
        self.frame_7 = QFrame(self.frame)
        self.frame_7.setMaximumSize(QSize(16777215, 30))
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_13 = QHBoxLayout(self.frame_7)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_5 = QLabel(self.frame_7)
        self.label_5.setMinimumSize(QSize(110, 0))
        self.label_5.setMaximumSize(QSize(110, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_13.addWidget(self.label_5)
        self.plainTextEdit_5 = QPlainTextEdit(self.frame_7)
        self.plainTextEdit_5.setMinimumSize(QSize(0, 25))
        self.plainTextEdit_5.setMaximumSize(QSize(16777215, 25))
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.horizontalLayout_13.addWidget(self.plainTextEdit_5)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.frame_6 = QFrame(self.frame)
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_14 = QHBoxLayout(self.frame_6)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_6 = QLabel(self.frame_6)
        self.label_6.setMinimumSize(QSize(110, 0))
        self.label_6.setMaximumSize(QSize(110, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_14.addWidget(self.label_6)
        self.pushButton_2 = QPushButton(self.frame_6)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_14.addWidget(self.pushButton_2)
        self.label_20 = QLabel(self.frame_6)
        self.label_20.setMinimumSize(QSize(140, 0))
        self.label_20.setMaximumSize(QSize(140, 16777215))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_14.addWidget(self.label_20)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_5 = QFrame(self.frame)
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_15 = QHBoxLayout(self.frame_5)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_7 = QLabel(self.frame_5)
        self.label_7.setMinimumSize(QSize(110, 0))
        self.label_7.setMaximumSize(QSize(110, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_15.addWidget(self.label_7)
        self.pushButton_3 = QPushButton(self.frame_5)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_15.addWidget(self.pushButton_3)
        self.pushButton_4 = QPushButton(self.frame_5)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_15.addWidget(self.pushButton_4)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QDialogButtonBox.Cancel | QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject)  # type: ignore
        QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_11.setText(_translate(
            "Dialog", "Surname:                   "))
        self.label_12.setText(_translate(
            "Dialog", "First Name:                "))
        self.label_13.setText(_translate("Dialog", "Other Names:            "))
        self.label_14.setText(_translate("Dialog", "Date of Birth:"))
        self.dateEdit.setDisplayFormat(_translate("Dialog", "dd/MM/yyyy"))
        self.label_3.setText(_translate("Dialog", "School:"))
        self.label_15.setText(_translate("Dialog", "Course:"))
        self.comboBox.setItemText(0, _translate("Dialog", "General Science"))
        self.comboBox.setItemText(1, _translate("Dialog", "Business"))
        self.comboBox.setItemText(2, _translate("Dialog", "Home Economics"))
        self.comboBox.setItemText(3, _translate("Dialog", "General Arts"))
        self.comboBox.setItemText(4, _translate("Dialog", "Visual Arts"))
        self.label_16.setText(_translate("Dialog", "Class:"))
        self.label_17.setText(_translate("Dialog", "BECE Index Number:"))
        self.label_18.setText(_translate("Dialog", "Year Completed:"))
        self.dateEdit_2.setDisplayFormat(_translate("Dialog", "yyyy"))
        self.label.setText(_translate("Dialog", "Electives"))
        self.checkBox_24.setText(_translate("Dialog", "Textile"))
        self.checkBox_5.setText(_translate("Dialog", "Geography"))
        self.checkBox_12.setText(_translate(
            "Dialog", "Ceramics and Sculpture"))
        self.checkBox_21.setText(_translate("Dialog", "Accounting"))
        self.checkBox_2.setText(_translate("Dialog", "Chemistry"))
        self.checkBox_17.setText(_translate("Dialog", "French"))
        self.checkBox_22.setText(_translate("Dialog", "Government"))
        self.checkBox_11.setText(_translate("Dialog", "Picture Making"))
        self.checkBox_14.setText(_translate("Dialog", "Food and Nutrition"))
        self.checkBox_4.setText(_translate("Dialog", "Literature in English"))
        self.checkBox_23.setText(_translate("Dialog", "Religious Studies"))
        self.checkBox.setText(_translate("Dialog", "Biology"))
        self.checkBox_20.setText(_translate("Dialog", "Leather Works"))
        self.checkBox_9.setText(_translate("Dialog", "Graphic Design"))
        self.checkBox_3.setText(_translate("Dialog", "Physics"))
        self.checkBox_6.setText(_translate("Dialog", "History"))
        self.checkBox_19.setText(_translate("Dialog", "Basketry"))
        self.checkBox_13.setText(_translate("Dialog", "Management in Living"))
        self.checkBox_8.setText(_translate("Dialog", "Principles of Costing"))
        self.checkBox_7.setText(_translate("Dialog", "Business Management"))
        self.checkBox_18.setText(_translate("Dialog", "Economics"))
        self.checkBox_16.setText(_translate("Dialog", "Elective Mathematics"))
        self.checkBox_10.setText(_translate(
            "Dialog", "General Knowledge in Arts"))
        self.checkBox_50.setText(_translate(
            "Dialog", "Elective ICT"))
        self.label_2.setText(_translate("Dialog", "Picture:"))
        self.pushButton.setText(_translate("Dialog", "Select File"))
        self.label_19.setText(_translate("Dialog", ""))
        self.label_4.setText(_translate("Dialog", "Gender:"))
        self.radioButton.setText(_translate("Dialog", "Male"))
        self.radioButton_2.setText(_translate("Dialog", "Female"))
        self.label_5.setText(_translate("Dialog", "Parent\'s Contact:"))
        self.plainTextEdit_5.setPlainText(_translate("Dialog", "+233"))
        self.label_6.setText(_translate("Dialog", "Signature:"))
        self.pushButton_2.setText(_translate("Dialog", "Select Image"))
        self.label_20.setText(_translate("Dialog", ""))
        self.label_7.setText(_translate("Dialog", "Fingerprint:"))
        self.pushButton_3.setText(_translate("Dialog", "Take Left Thumb"))
        self.pushButton_4.setText(_translate("Dialog", "Take Right Thumb"))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    Dialog = QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
